# Generated by Django 2.2.4 on 2019-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=100)),
                ('rating', models.CharField(default='3', max_length=100)),
                ('comments', models.TextField(max_length=5000)),
            ],
        ),
    ]
